# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Littlefuse' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Littlefuse

  target 'LittleFuseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LittleFuseUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'NSHash', '~> 1.1.0'

end
